name: CI

on:
    push:
        branches: ["*"]
        tags: ["*"]
    pull_request:
        branches: ["*"]
        tags: ["*"]
    workflow_dispatch:

jobs:
    cache:
        name: caching packages on ${{ matrix.platform }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/cache@v3
              with:
                path: ~/.cache
                key: |
                    ${{ runner.os }}-${{ github.sha }}
                restore-keys: |
                    ${{ runner.os }}-${{ github.sha }}
            - name: create cache directory
              if: steps.ccache-restore.outputs.cache-hit != 'true'
              run: mkdir -p ~/.cache

    build:
        name: compiling on ${{ matrix.platform }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: recursive
                fetch-depth: 0
            - name: compiling
              run: cmake --build ./build/
